artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://raw.githubusercontent.com/RS4327/RAWDATA/main/cancer_dataset.csv"
  local_data_file: artifacts/data_ingestion/cancer_dataset.csv